# Generated by Django 5.2 on 2025-06-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_customuser_city_remove_customuser_pin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='language',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='notifications_enabled',
        ),
    ]
