# Generated by Django 5.2 on 2025-06-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_usersettings_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='Tamil Nadu', max_length=100),
        ),
    ]
